language: python
python:
  - 3.6
sudo: required
addons:
  chrome: stable
services:
  - xvfb
  - postgresql
cache:
  pip: true
  yarn: true
  directories:
install:
  - pip install -r requirements.txt -r requirements-dev.txt -r requirements-postgres.txt
  - pushd frontend; yarn install; popd
before_script:
  - wget "https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
script:
  - python -m coverage run --source rfhub2 -m unittest -b tests
  - black --check -t py36 rfhub2 tests
  - ./build_ui.sh
  - python setup.py sdist bdist_wheel
  - rm test.db  #ensure we start clean slate
  - ./scripts/install_package_in_venv.sh
  - robot -A tests/acceptance/conf/default.args tests/acceptance
  - robot -A tests/acceptance/conf/postgres.args tests/acceptance
after_success:
  - codecov
  - python publish_pypi.py
deploy:
  provider: heroku
  app: rfhub2-demo
  api_key: $HEROKU_AUTH_TOKEN
